(() => {
  const qs = new URLSearchParams(location.search), token = qs.get('owner_token');
  const request = async (email) => { const r = await fetch('/api/admin-link', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); return r.ok; };
  const session = async () => token ? (await fetch(`/api/admin-session?token=${encodeURIComponent(token)}`)).ok : (await fetch('/api/settings')).ok;
  const loadRemote = async () => { const response = await fetch('/api/settings'); if (!response.ok) return; const remote = await response.json(); document.querySelectorAll('[data-key]').forEach((el) => { if (remote[el.dataset.key] !== undefined) el.value = remote[el.dataset.key]; }); document.querySelectorAll('[data-price]').forEach((el) => { if (remote[el.dataset.price] !== undefined) el.value = remote[el.dataset.price]; }); };
  const markConnected = async () => { document.title = "Michelle's Catering · Owner Dashboard"; const save = document.querySelector('#saveAll'); if (save) save.textContent = 'Save changes'; const mode = document.querySelector('.admin-stat strong'); if (mode) mode.textContent = 'Live'; const copy = document.querySelector('.admin-top p:not(.eyebrow)'); if (copy) copy.textContent = 'Secure owner controls. Changes save to the shared production dashboard.'; document.querySelectorAll('.admin-panel>p').forEach((p) => { if (/saved only in this browser|saved locally only|until production persistence/i.test(p.textContent)) p.textContent = 'Changes save to the shared production dashboard.'; }); await loadRemote(); };
  session().then(async (ok) => { if (token && ok) history.replaceState({}, '', location.pathname); if (ok) { await markConnected(); return; } const box = document.createElement('div'); box.className = 'admin-login'; box.innerHTML = '<div class="admin-login-card"><h2>Owner sign-in</h2><p>Enter the owner email to receive a secure dashboard link.</p><form><input type="email" required placeholder="fifynow@gmail.com" aria-label="Owner email"><button class="admin-button primary">Email me a sign-in link</button><p role="status"></p></form></div>'; document.body.prepend(box); box.querySelector('form').addEventListener('submit', async (e) => { e.preventDefault(); const status = box.querySelector('[role=status]'); status.textContent = 'Sending…'; status.textContent = await request(box.querySelector('input').value) ? 'If that owner email is registered, a sign-in link is on its way.' : 'Unable to send the sign-in link.'; }); document.querySelectorAll('.admin-section,.admin-nav,.admin-actions,.admin-grid,.admin-note').forEach((el) => { el.hidden = true; }); });
  document.querySelector('#saveAll')?.addEventListener('click', async () => { if (!document.querySelector('.admin-login')) { const settings = {}; document.querySelectorAll('[data-key]').forEach((el) => { settings[el.dataset.key] = el.value; }); document.querySelectorAll('[data-price]').forEach((el) => { settings[el.dataset.price] = el.value.trim() || 'Quote'; }); const r = await fetch('/api/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); const s = document.querySelector('#adminStatus'); if (s) s.textContent = r.ok ? 'Saved to the shared production dashboard.' : 'Could not save to production; local copy retained.'; } });
})();
