import { neon } from '@neondatabase/serverless';
import { sessionRole } from './_team-auth.js';
const safe=(value,max)=>String(value||'').trim().slice(0,max);
const sanitizeHtml=(value)=>String(value||'').replace(/<\\s*(script|style|iframe|object|embed|form|svg|math)[^>]*>[\\s\\S]*?<\\s*\\/\\s*\\1\\s*>/gi,'').replace(/\\son\\w+\\s*=\\s*("[^"]*"|'[^']*'|[^\\s>]+)/gi,'').replace(/\\sstyle\\s*=\\s*("[^"]*"|'[^']*'|[^\\s>]+)/gi,'').replace(/\\s(href|src)\\s*=\\s*("|')\\s*javascript:[\\s\\S]*?\\2/gi,'').replace(/\\s(href|src)\\s*=\\s*("|')(?!https?:|mailto:|tel:|\\/|#)[\\s\\S]*?\\2/gi,'');
export default async function handler(req,res){
  const access=await sessionRole(req);
  if(!access)return res.status(401).json({error:'Admin sign-in required'});
  if(access==='viewer')return res.status(403).json({error:'Viewer access is read-only'});
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  const subject=safe(req.body?.subject,160),html=sanitizeHtml(safe(req.body?.html,12000)),text=safe(req.body?.text,5000);
  if(!subject||!html)return res.status(400).json({error:'Subject and HTML content are required'});
  if(!process.env.DATABASE_URL||!process.env.RESEND_API_KEY||!process.env.RESEND_FROM_EMAIL)return res.status(503).json({error:'Broadcast sender or database is not configured'});
  const from=String(process.env.RESEND_FROM_EMAIL).trim(),base=process.env.PUBLIC_SITE_URL||'https://michelles-catering-service.vercel.app';
  try{const sql=neon(process.env.DATABASE_URL);await sql`CREATE TABLE IF NOT EXISTS marketing_subscribers (id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,consented_at TIMESTAMPTZ NOT NULL DEFAULT now(),unsubscribed_at TIMESTAMPTZ NULL,source TEXT NOT NULL DEFAULT 'website')`;await sql`CREATE TABLE IF NOT EXISTS marketing_campaigns (id BIGSERIAL PRIMARY KEY,subject TEXT NOT NULL,recipient_count INTEGER NOT NULL DEFAULT 0,sent_count INTEGER NOT NULL DEFAULT 0,failed_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;const rows=await sql`SELECT email FROM marketing_subscribers WHERE unsubscribed_at IS NULL ORDER BY id LIMIT 200`;if(!rows.length)return res.status(200).json({ok:true,recipientCount:0,sent:0,failed:0,message:'No consented subscribers yet.'});let sent=0,failed=0;for(const row of rows){const unsubscribe=`${base}/api/unsubscribe?email=${encodeURIComponent(row.email)}`;const body={from,to:[row.email],reply_to:from,subject,headers:{'List-Unsubscribe':`<${unsubscribe}>`,'List-Unsubscribe-Post':'List-Unsubscribe=One-Click'},html:`<div style="max-width:640px;margin:auto;font-family:Arial,sans-serif;color:#22302d"><div style="background:#173b35;padding:22px;color:#fff"><strong style="color:#f4c26b;letter-spacing:2px">MICHELLE'S CATERING SERVICE</strong></div><div style="background:#fff;padding:26px">${html}<hr><p style="font-size:12px;color:#667">You are receiving Michelle’s Catering updates because you subscribed on the website. <a href="${unsubscribe}">Unsubscribe</a></p></div></div>`,text:`${text||subject}\n\nMichelle's Catering Service\n\nUnsubscribe: ${unsubscribe}`};try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});response.ok?sent++:failed++}catch{failed++}}await sql`INSERT INTO marketing_campaigns (subject,recipient_count,sent_count,failed_count) VALUES (${subject},${rows.length},${sent},${failed})`;return res.status(200).json({ok:true,recipientCount:rows.length,sent,failed})}catch(error){console.error('Broadcast failed',error);return res.status(503).json({error:'Broadcast service unavailable'})}}
